version: "3.9"

services:
  web:
    image: kamal2411/todo-app:latest
    container_name: todo-web
    env_file:
      - .env
    ports:
      - "80:5001"
    depends_on:
      - mysql
      - redis
    networks:
      - todo-network

  mysql:
    image: mysql:8.0
    container_name: todo-mysql
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - todo-network

  redis:
    image: redis:7-alpine
    container_name: todo-redis
    ports:
      - "6379:6379"
    networks:
      - todo-network

volumes:
  mysql_data:

networks:
  todo-network:
    driver: bridge
